#!/usr/bin/bash

apt-get install \
ninja-build  \
libglib2.0-dev \
libpixman-1-dev \
libpmem-dev \
libfuse3-dev \
ubuntu-dev-tools \
libvdeplug-dev \
libjack-dev \
libvirglrenderer-dev \
multipath-tools \
libsdl2-dev \
libsdl2-image-dev \
libglusterfs-dev \
libgbm-dev \
libpam0g-dev \
libcacard-dev \
doxygen \
graphviz \
cmake \
libusbredirparser-dev \
libusb-1.0-0-dev \
libkeyutils-dev \
libelf-dev \
libdrm-dev \
libslirp-dev \
sparse \
libaio-dev \
libxml2-dev \
libnfs-dev \
libseccomp-dev \
libcap-ng-dev \
libspice-protocol-dev \
libspice-server-dev \
libiscsi-dev \
libzstd-dev \
libcurl4-gnutls-dev \
libncurses-dev \
libbrlapi-dev \
libbz2-dev \
librbd-dev \
libgcrypt20-dev \
libgtk-3-dev \
libvte-2.91-dev \
libjpeg-dev \
libsasl2-dev \
libsnappy-dev \
liblzo2-dev \
libdaxctl-dev \
valgrind \
gettext \
libssl-dev \
python3-sphinx \
autoconf \
libltdl-dev \
autoconf-archive \
libssh-dev \
xfslibs-dev \
locate \
libpython3-dev \
libpython3.8-dev \
pandoc-data \
python3.8-dev \
uml-utilities \
bridge-utils \
isc-dhcp-server

